// <auto-generated />
namespace D2DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NavigationProps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NavigationProps));
        
        string IMigrationMetadata.Id
        {
            get { return "201503130752590_NavigationProps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
